name: dimspy
channels:
  - conda-forge
  - bioconda
dependencies:
 - python=3.7
 - mono # https://www.mono-project.com/
 - numpy=1.16.2
 - scipy=1.1.0
 - pymzml=2.2.3
 - h5py=2.8.0
 - pythonnet=2.4.0
 - fastcluster=1.1.25
 - pytables=3.5.2
 
